# Generated by Django 5.2.8 on 2025-11-11 07:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="KnowledgeGraphStatistics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("total_nodes", models.IntegerField(default=0)),
                ("total_relationships", models.IntegerField(default=0)),
                ("user_nodes", models.IntegerField(default=0)),
                ("video_nodes", models.IntegerField(default=0)),
                ("topic_nodes", models.IntegerField(default=0)),
                ("source_nodes", models.IntegerField(default=0)),
                ("entity_nodes", models.IntegerField(default=0)),
                (
                    "statistics_data",
                    models.JSONField(
                        default=dict, help_text="Additional graph statistics"
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "get_latest_by": "timestamp",
            },
        ),
        migrations.CreateModel(
            name="VideoSummarizationRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("video_id", models.CharField(db_index=True, max_length=255)),
                ("topic", models.CharField(max_length=500)),
                ("source", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "payload",
                    models.JSONField(help_text="Original video summarization payload"),
                ),
                (
                    "processing_result",
                    models.JSONField(
                        blank=True,
                        help_text="Processing result from pipeline",
                        null=True,
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, help_text="Error message if processing failed"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("processing_started_at", models.DateTimeField(blank=True, null=True)),
                (
                    "processing_completed_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("processing_time_seconds", models.FloatField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="summarization_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["video_id", "status"],
                        name="graph_video_video_i_2a0633_idx",
                    ),
                    models.Index(
                        fields=["user", "created_at"],
                        name="graph_video_user_id_97b2ab_idx",
                    ),
                    models.Index(
                        fields=["status", "created_at"],
                        name="graph_video_status_149e71_idx",
                    ),
                ],
            },
        ),
    ]
