# Generated by Django 5.2.8 on 2025-11-19 08:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("graph", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="knowledgegraphstatistics",
            old_name="video_nodes",
            new_name="post_nodes",
        ),
        migrations.CreateModel(
            name="TextProcessingRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("post_id", models.CharField(db_index=True, max_length=255)),
                ("topic", models.CharField(max_length=500)),
                ("source", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "payload",
                    models.JSONField(help_text="Original text processing payload"),
                ),
                (
                    "processing_result",
                    models.JSONField(
                        blank=True,
                        help_text="Processing result from pipeline",
                        null=True,
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, help_text="Error message if processing failed"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("processing_started_at", models.DateTimeField(blank=True, null=True)),
                (
                    "processing_completed_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("processing_time_seconds", models.FloatField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="text_processing_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.DeleteModel(
            name="VideoSummarizationRequest",
        ),
        migrations.AddIndex(
            model_name="textprocessingrequest",
            index=models.Index(
                fields=["post_id", "status"], name="graph_textp_post_id_592358_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="textprocessingrequest",
            index=models.Index(
                fields=["user", "created_at"], name="graph_textp_user_id_6020b5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="textprocessingrequest",
            index=models.Index(
                fields=["status", "created_at"], name="graph_textp_status_435f7c_idx"
            ),
        ),
    ]
