# Generated by Django 5.2.8 on 2025-11-21 13:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_id', models.CharField(db_index=True, max_length=500, unique=True)),
                ('platform', models.CharField(choices=[('bluesky', 'Bluesky'), ('tiktok', 'TikTok')], max_length=20)),
                ('author', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('media_url', models.URLField(blank=True, max_length=500, null=True)),
                ('thumbnail_url', models.URLField(blank=True, max_length=500, null=True)),
                ('like_count', models.IntegerField(default=0)),
                ('repost_count', models.IntegerField(default=0)),
                ('reply_count', models.IntegerField(default=0)),
                ('created_at_source', models.DateTimeField(blank=True, null=True)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalFeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('user_intent', models.TextField(help_text='Prompt gốc của user')),
                ('search_queries', models.JSONField(default=list)),
                ('include_criteria', models.TextField()),
                ('exclude_criteria', models.TextField()),
                ('platform', models.CharField(choices=[('bluesky', 'Bluesky'), ('tiktok', 'TikTok')], default='bluesky', max_length=20)),
                ('ranking_style', models.CharField(choices=[('balanced', 'Balanced'), ('focused', 'Focused'), ('fresh', 'Fresh'), ('trending', 'Trending')], default='balanced', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feeds', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FeedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ai_score', models.FloatField()),
                ('ai_reasoning', models.TextField()),
                ('ai_summary', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='feed.personalfeed')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feed.socialpost')),
            ],
            options={
                'ordering': ['-ai_score'],
                'unique_together': {('feed', 'post')},
            },
        ),
    ]
