# Generated by Django 5.2.8 on 2025-11-21 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalfeed',
            name='exclude_criteria',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='personalfeed',
            name='include_criteria',
            field=models.TextField(blank=True, default=''),
        ),
    ]
