# Generated by Django 5.2.8 on 2025-11-22 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_alter_personalfeed_exclude_criteria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialpost',
            name='source_link',
            field=models.URLField(blank=True, help_text='Link post for user to click to view', max_length=500, null=True),
        ),
    ]
