# Generated by Django 5.2.8 on 2025-11-22 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0003_socialpost_source_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialpost',
            name='embed_quote',
            field=models.TextField(blank=True, help_text='HTML Embed of TikTok', null=True),
        ),
    ]
